### PR TITLE
Rename docker entrypoint file

### PR DESCRIPTION
**Pull request by sdurban**
As seen in course the filename was mismatched with the entrypoint in Dockerfile.

### CODE REVIEW

**Comment by mmoreram** [comment]
@sdurban if you rename one entrypoint, make sure that you rename the other as well XD

**Comment by sdurban** [comment]
@mmoreram True! I will update pr tomorrow.

Didn't saw the docker-compose entrypoint, I was just avoiding spoilers 🙉.

**Comment by sdurban** [comment]
@mmoreram Fixed problems with "names".

**Comment by mmoreram** [comment]
Great @sdurban , Thanks!

**Pull request merged**
